import { Transaction } from '../types';

export const mockTransactions: Transaction[] = [
  {
    id: 'txn-001',
    title: 'Spring Hackathon Fundraiser',
    amount: 850,
    direction: 'Inflow',
    type: 'Fundraiser deposit',
    fundingSource: 'Fundraiser',
    budgetLine: 'Operating',
    person: 'Amara Johnson',
    date: '2026-03-28',
    status: 'Submitted',
    hasReceipt: true,
    hasSignature: true,
    notes: 'Hackathon ticket sales and sponsorships',
  },
  {
    id: 'txn-002',
    title: 'ASG Spring Allocation',
    amount: 1200,
    direction: 'Inflow',
    type: 'Transfer',
    fundingSource: 'ASG',
    budgetLine: 'ASG',
    person: 'Marcus Williams',
    date: '2026-03-25',
    status: 'Submitted',
    hasReceipt: true,
    hasSignature: true,
    notes: 'Quarterly ASG budget allocation',
  },
  {
    id: 'txn-003',
    title: 'Tech Conference Supplies',
    amount: 148.5,
    direction: 'Outflow',
    type: 'Reimbursement',
    fundingSource: 'ASG',
    budgetLine: 'ASG',
    person: 'Jordan Lee',
    date: '2026-03-27',
    status: 'Ready',
    hasReceipt: true,
    hasSignature: false,
    notes: 'Name tags, markers, poster boards',
  },
  {
    id: 'txn-004',
    title: 'Pizza for General Meeting',
    amount: 87.43,
    direction: 'Outflow',
    type: 'Debit card purchase',
    fundingSource: 'ASG',
    budgetLine: 'Debit Card',
    person: 'Priya Patel',
    date: '2026-03-26',
    status: 'Submitted',
    hasReceipt: true,
    hasSignature: true,
    notes: '',
  },
  {
    id: 'txn-005',
    title: 'Alumni Gift Donation',
    amount: 500,
    direction: 'Inflow',
    type: 'Transfer',
    fundingSource: 'Gift',
    budgetLine: 'Gifts',
    person: 'Sarah Chen',
    date: '2026-03-24',
    status: 'Submitted',
    hasReceipt: true,
    hasSignature: true,
    notes: 'Unrestricted gift from alumni donor',
  },
  {
    id: 'txn-006',
    title: 'Printing Reimbursement',
    amount: 32.1,
    direction: 'Outflow',
    type: 'Reimbursement',
    fundingSource: 'SOFO',
    budgetLine: 'Operating',
    person: 'David Kim',
    date: '2026-03-22',
    status: 'Draft',
    hasReceipt: false,
    hasSignature: false,
    notes: 'Need to attach receipt from library print center',
  },
  {
    id: 'txn-007',
    title: 'Mentorship Kickoff Dinner',
    amount: 215.0,
    direction: 'Outflow',
    type: 'Direct payment',
    fundingSource: 'SOFO',
    budgetLine: 'Operating',
    person: 'Amara Johnson',
    date: '2026-03-20',
    status: 'Ready',
    hasReceipt: false,
    hasSignature: true,
    notes: 'Annual mentorship program kickoff',
  },
  {
    id: 'txn-008',
    title: 'SOFO Spring Funds',
    amount: 600,
    direction: 'Inflow',
    type: 'Transfer',
    fundingSource: 'SOFO',
    budgetLine: 'Operating',
    person: 'Marcus Williams',
    date: '2026-03-18',
    status: 'Submitted',
    hasReceipt: true,
    hasSignature: true,
    notes: '',
  },
  {
    id: 'txn-009',
    title: 'Office Supplies Purchase',
    amount: 45.67,
    direction: 'Outflow',
    type: 'Debit card purchase',
    fundingSource: 'ASG',
    budgetLine: 'Debit Card',
    person: 'Jordan Lee',
    date: '2026-03-15',
    status: 'Draft',
    hasReceipt: true,
    hasSignature: false,
    notes: '',
  },
  {
    id: 'txn-010',
    title: 'Industry Panel Snacks',
    amount: 63.2,
    direction: 'Outflow',
    type: 'Reimbursement',
    fundingSource: 'ASG',
    budgetLine: 'ASG',
    person: 'Priya Patel',
    date: '2026-03-12',
    status: 'Submitted',
    hasReceipt: true,
    hasSignature: true,
    notes: '',
  },
];
