import { Transaction } from '../types';

export const mockTransactions: Transaction[] = [
  {
    id: 'txn-001',
    title: 'Spring Hackathon Fundraiser',
    amount: 850,
    direction: 'Inflow',
    type: 'Deposit',
    funding: 'Operating',
    budgetLine: 'Operating',
    notes: 'Hackathon ticket sales and sponsorships',
  },
  {
    id: 'txn-002',
    title: 'ASG Spring Allocation',
    amount: 1200,
    direction: 'Inflow',
    type: 'Deposit',
    funding: 'ASG',
    budgetLine: 'ASG',
    notes: 'Quarterly ASG budget allocation',
  },
  {
    id: 'txn-003',
    title: 'Tech Conference Supplies',
    amount: 148.5,
    direction: 'Outflow',
    type: 'Reimbursement',
    funding: 'ASG',
    budgetLine: 'ASG',
    notes: 'Name tags, markers, poster boards',
  },
  {
    id: 'txn-004',
    title: 'Pizza for General Meeting',
    amount: 87.43,
    direction: 'Outflow',
    type: 'Debit card purchase',
    budgetLine: 'Debit Card',
    notes: '',
  },
  {
    id: 'txn-005',
    title: 'Alumni Gift Donation',
    amount: 500,
    direction: 'Inflow',
    type: 'Deposit',
    funding: 'Gifts',
    budgetLine: 'Gifts',
    notes: 'Unrestricted gift from alumni donor',
  },
  {
    id: 'txn-006',
    title: 'Printing Reimbursement',
    amount: 32.1,
    direction: 'Outflow',
    type: 'Reimbursement',
    funding: 'Operating',
    budgetLine: 'Operating',
    notes: '',
  },
  {
    id: 'txn-007',
    title: 'Mentorship Kickoff Dinner',
    amount: 215.0,
    direction: 'Outflow',
    type: 'Direct payment',
    funding: 'Operating',
    budgetLine: 'Operating',
    notes: 'Annual mentorship program kickoff',
  },
  {
    id: 'txn-008',
    title: 'SOFO Spring Funds',
    amount: 600,
    direction: 'Inflow',
    type: 'Deposit',
    funding: 'Operating',
    budgetLine: 'Operating',
    notes: '',
  },
  {
    id: 'txn-009',
    title: 'Office Supplies Purchase',
    amount: 45.67,
    direction: 'Outflow',
    type: 'Debit card purchase',
    budgetLine: 'Debit Card',
    notes: '',
  },
  {
    id: 'txn-010',
    title: 'Industry Panel Snacks',
    amount: 63.2,
    direction: 'Outflow',
    type: 'Reimbursement',
    funding: 'ASG',
    budgetLine: 'ASG',
    notes: '',
  },
];
